### ISSUE TITLE
Roadmap for NDN Workspace

### ISSUE THREAD

**Issue by zjkmxy** [UCLA-IRL/ndn-workspace-solid#30]
The development plan we discussed during the 15th NDN Hackathon.

## Rollout Stages

- OpenID and compiler support
- Fallback bootstrapping plan
- UI & UX improvement
- Encryption and repo collaboration
- Publish for the public preview (have NDN team try it)

Based on this plan, we have organized the issues into three categories

## December 2023

- [x] #32 : OpenID Support. In this model, membership is solely managed by the owner of the workspace.
- [x] #5 : Write a basic LaTeX server

- [x] #21 : Actually already works. A-Frame related things have some images not cached.
- [x] #17 : Needs further discussion about names and will be brought up in the Friday call.
- [x] #16 : Issue identified. No need to solve now, just manually reconnect.
- [x] #9 
- [X] #4 (local snapshot only)

## Now

- [ ] #44 : (11/30/2023) Web-of-trust model-based bootstrapping.
- [x] #20 
- [ ] #25 : To simplify the implementation, we will use a shared group key for encryption.
- [x] #11 
- [ ] #4 : For quick solution, we plan to take snapshots at a fixed rate w.r.t. sequence numbers (#90).
- [x] #45
- [x] #69 : Add chat functionality.

## Future

- [ ] #19 : Already supported by NDNts. We only need to use it.
- [ ] #26 (access control)
  - [ ] #18 
  - [ ] #10 
- [ ] #7 : This somehow related to certificate renewal. Before that, we can keep the current implementation
- [x] #27 : Web apps do not need to be tested, as it is hard and easy to break. Backend may be tested if necessary.
- [x] #3 : This is for mobile devices. An easy fix but delay until someone has time cycle or we received claims from users.
- [ ] #24 : Not an urgent feature at all. Maybe just before release.
- [ ] #23 : Though useful, it is optimal
  - [ ] #22 
- [ ] #15 : Not very necessary.
- [ ] #14 : Maybe not necessary.

## UI Improvement

UI improvement not included in any specific milestone. Please contribute if you like.
There are more in the issues page not listed here.

- [ ] #66 
- [ ] #68 
- [ ] #74 
- [x] #84 
- [ ] #85 
- [ ] #86 
- [x] #87 
- [x] #89

**Comment by zjkmxy** [comment]
This is out of dated. Let me create a new list.
